# -*- coding: utf-8 -*-
"""Copy of Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRRlmDFqq3mFcKxxkGBWCaMT2EWY0hsB
"""

# Derin Öğrenmenin Temelleri Proje.
# Defect Detection in Industrial Products.
# PCB

# Tespit Edebileceklerimiz
"""
0 – mouse_bite:
PCB kenarında fare ısırığı gibi küçük çentikler.

1 – spur:
İstenmeyen ince bakır çıkıntısı (kıl gibi uzantı).

2 – missing_hole:
Açılması gereken delik/via’nın hiç açılmamış olması.

3 – short:
İki bakır hattın kazara birleşip kısa devre oluşturması.

4 – open_circuit:
Bir bakır hattın kopması; bağlantının kesilmesi.

5 – spurious_copper:
Kart üzerinde gereksiz, şemaya ait olmayan bakır parçaları.
"""

# LINUX ORTAMINDAYIZ

!uname -a

!nvidia-smi

from google.colab import drive
drive.mount('/content/drive') # drive'mizi colab'a bağlıyoruz.

# Drive'dan /content'e komple kopyala
!cp -r "/content/drive/MyDrive/Burcu Hoca Proje/Project/pcb-defect-dataset" "/content/pcb-defect-dataset"

import yaml

yaml_yolu = "/content/pcb-defect-dataset/data.yaml"

with open(yaml_yolu, "r") as f:
    data = yaml.safe_load(f)

# Drive yerine content dizinini gösterelim
data["path"] = "/content/pcb-defect-dataset"
data["train"] = "train"
data["val"] = "val"
data["test"] = "test"

with open(yaml_yolu, "w") as f:
    yaml.safe_dump(data, f, sort_keys=False)

print("✅ data.yaml güncellendi!")
print(open(yaml_yolu).read())

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/iMoonLab/yolov13.git
# %cd yolov13

# requirements.txt
with open("requirements.txt", "w") as f:
    f.write("""torch>=2.2.0
torchvision>=0.17.0
torchaudio>=2.2.0
tqdm
PyYAML
numpy
opencv-python>=4.8.0
pillow>=10.0.0
matplotlib
scipy
ultralytics>=8.3.63
supervision>=0.22.0
onnx==1.14.0
onnxruntime-gpu>=1.17.1
albumentations>=1.3.1
psutil
gradio""")

!pip install -r requirements.txt
!pip install -e .

import shutil, os

base = "/content/yolov13/ultralytics/cfg/models/v13/yolov13.yaml"
target_dir = os.path.dirname(base)

for variant in ["n", "s", "l", "x"]:
    new_yaml = os.path.join(target_dir, f"yolov13{variant}.yaml")
    shutil.copy(base, new_yaml)
    with open(new_yaml, "r") as f:
        lines = f.readlines()
    with open(new_yaml, "w") as f:
        f.write(f"# Auto-generated {variant} model\nscale: \"{variant}\"\n")
        f.writelines(lines)
    print("✅ Created:", new_yaml)

# Drive bağlantısı
from google.colab import drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

from ultralytics import YOLO

# Model
model = YOLO("/content/yolov13/ultralytics/cfg/models/v13/yolov13s.yaml")

# --- A100 80GB ayarlaması-
results = model.train(
    data="/content/pcb-defect-dataset/data.yaml",
    epochs=50,
    imgsz=640,

    # otomatik batch size
    batch=-1,

    device="cuda",

    # 2. Hızlandırma Ayarları
    workers=16,      # CPU GPU'ya veri yetiştirmek için kullanacak,çekirdek sayısı
    cache=True,      # RAM'den oku

    # 3. Drive kaydetme
    project="/content/drive/MyDrive/YOLO_Egitimleri",
    name="pcb_yolo13s_A100_Final",
    save=True,
    save_period=1,   # Her epoch'ta

    # Optimizasyon Ayarların
    optimizer="SGD", # optimizasyon algoritmamız
    lr0=0.01, # öğrenme hızı
    momentum=0.937, # modelin önceki adımlarla bağlı olmasını sağlar
    cos_lr=True, # learning rateyi dalgalı şekilde yürütür
    close_mosaic=10, # Son 10 epochta 4 farklı resim üzerinden eğitim metodunu kapatır
    patience=20, # erken durdurma,ancak geniş optimizasyon aralığında
    amp=True # hesaplamaları hassas yapması için
)

import torch, gc
# gpu memory boşalt
def clear_gpu_memory():
    print("GPU memory'sini boşalt")
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()
    print("✅ Kalan kullanım:",
          f"{torch.cuda.memory_allocated()/1024**2:.1f} MB / {torch.cuda.get_device_properties(0).total_memory/1024**2:.1f} MB")

clear_gpu_memory()

# RAM boşaltmak için,gerekli durumlarda.

import os
os.kill(os.getpid(), 9)

